"""add -> description field to institutions model

Revision ID: b1ae37d36870
Revises: c3c90463cc22
Create Date: 2025-06-09 20:59:03.798088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ae37d36870'
down_revision: Union[str, None] = 'c3c90463cc22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'description')
    # ### end Alembic commands ###
